In [1]:
import numpy as np

In [2]:
# Array-陣列
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# A. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

In [3]:
print("list(a):", list(a))
print("tolist():", a.tolist())

list(a): [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist(): [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


#Ans
list(a) => list 裡的每個元素是一個 ndarray；如上，list 是由 3 個 ndarray 組成
a.tolist() => list 裡的每個元素是另一個 list；如上，list 是由 3 個 list 組成
=> list(a) 只能將 array 降一個維度變成 list，使得 list 由 ndarray 組成；而 a.tolist() 則可以將 array 全拆解成 list

# B. 請試著在程式中印出以下三個 NdArray 的屬性？

In [4]:
a=np.random.randint(10, size=6)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
len(a)
type(a)

1
(6,)
6
int32
4


numpy.ndarray

In [5]:
b=np.random.randint(10, size=(3,4))
print(b.ndim) #2
print(b.shape) #(3,4)
print(b.size) #12
print(b.dtype) #int32
print(b.itemsize)
len(b)
type(b) #ndarray

2
(3, 4)
12
int32
4


numpy.ndarray

In [6]:
c=np.random.randint(10, size=(2,3,2))
print(c.ndim) #3
print(c.shape) #(2,3,2)
print(c.size) #12
print(c.dtype) #int32
print(c.itemsize)
len(c)
type(c) #ndarray

3
(2, 3, 2)
12
int32
4


numpy.ndarray

# C. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [7]:
# Array-陣列
a = np.arange(15).reshape(3,5)
print(a)
print("list(a):", list(a))
print("tolist():", a.tolist())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
list(a): [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist(): [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


In [8]:
b=[list(list(a)[0]),list(list(a)[1]),list(list(a)[2])]
print(b)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
